#define pedir_kilometros "Ingrese los kilometros recorridos (-1 para terminar): "
#define msj_error_ingreso "El numero ingresado no es correcto."
#define msj_combustible "Ingrese el precio del combustible por litro: "
#define msj_monto "Ingrese el monto total utilizado para esta compra"
#define msj_rendimiento "Redimiento (l/100km) de este tanque >> "
#define msj_rendpromedio "Rendimiento promedio (l/100km) >> "
#define msj_mejorrend "Mejor rendimiento (l/100km) >> "
#define msj_peorrend "Peor rendimiento (l/100km) >> "
#define msj_distanciatotal "Distancia total recorrida (km) >> "
#define msj_combustibletotal "Combustible total consumidos (l) >> "
#define msj_costototal "Costo total de su vehiculo ($) >> "
#define msj_error_prefijo "ERROR:"
